export default {
  appName: '',
  siteName: 'Starter Template',
  siteUrl: '#',
  gulpTasks: 'gulp-tasks',
  meta: 'preview',
  source: 'src',
  appRoot: 'src/app',
  prod: 'build',
  dev: '.tmp',
  db: 'src/app/db',
  assets: 'src/assets',
  assetsOut: 'assets',
  fonts: 'src/assets/fonts',
  images: 'src/assets/images',
  imagesOut: 'assets/images',
  videos: 'src/assets/videos',
  svgInline: 'src/assets/svg/inline',
  svgSprite: 'src/assets/svg/sprite',
  pngSprite: 'src/assets/png',
  hbs: 'src/app/hbs',
  styles: 'src/app/scss',
  scripts: 'src/app/scripts',
  scriptsOut: 'scripts',
  dynamicEntry: false,
  jsMin: true,
  cssMin: true,
  imageMin: false,
  criticalCss: false,
  babel: true,
  buildWebp: false,
}
