module.exports = [
  './gulp-tasks/assets',
  './gulp-tasks/clean',
  // './gulp-tasks/critical-css',
  // './gulp-tasks/deploy',
  './gulp-tasks/hbs',
  './gulp-tasks/image-min',
  './gulp-tasks/meta',
  // './gulp-tasks/png-sprite',
  './gulp-tasks/prepare-html-dev',
  './gulp-tasks/prepare-html-build',
  // './gulp-tasks/prepare-html-prod',
  './gulp-tasks/scripts',
  './gulp-tasks/server',
  // './gulp-tasks/sitemap',
  './gulp-tasks/styles',
  './gulp-tasks/svg',
  // './gulp-tasks/watch',
  './gulp-tasks/webp',
]
