module.exports = [
  './gulp-tasks/serve',
  './gulp-tasks/watch',
  './gulp-tasks/clean',
  './gulp-tasks/styles',
  // './gulp-tasks/hbs',
  // './gulp-tasks/hbs-prod',
  // './gulp-tasks/assets',
  // './gulp-tasks/svg-sprite',
  // './gulp-tasks/scripts',
  // './gulp-tasks/prepare-html-dev',
  // './gulp-tasks/prepare-html-build',
  // './gulp-tasks/prepare-html-prod',
  // './gulp-tasks/meta',
  // './gulp-tasks/image-min',
  // './gulp-tasks/deploy',
  // './gulp-tasks/sitemap',
  // './gulp-tasks/webp',
];
